import "FolderMonitorPageViewModel.idl";

namespace WindowsNativeToolkit
{
    [default_interface]
    runtimeclass FolderMonitorPage : Microsoft.UI.Xaml.Controls.Page
    {
        FolderMonitorPage();
        WindowsNativeToolkit.FolderMonitorPageViewModel ViewModel();
    }
}