import "ToolkitCore.winmd";

namespace WindowsNativeToolkit
{
    [default_interface]
    runtimeclass FolderMonitorPage : Windows.UI.Xaml.Controls.Page
    {
        FolderMonitorPage();
        Int32 MyProperty;
    }
}
